/foxglove_bridge:
  ros__parameters:
    port: 8765
    address: "0.0.0.0"
    num_threads: 0
    capabilities: ["clientPublish","parameters","parametersSubscribe","services","connectionGraph","assets"]
